/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProjectCategory = IDL.Variant({
  'Interior' : IDL.Null,
  'Architectural' : IDL.Null,
  'SpacePlanning' : IDL.Null,
  'Renovation' : IDL.Null,
});
export const ProjectInput = IDL.Record({
  'title' : IDL.Text,
  'featured' : IDL.Bool,
  'imageUrls' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'scope' : IDL.Text,
  'outcomes' : IDL.Text,
  'materials' : IDL.Vec(IDL.Text),
  'category' : ProjectCategory,
});
export const ProjectId = IDL.Nat;
export const Project = IDL.Record({
  'id' : ProjectId,
  'title' : IDL.Text,
  'featured' : IDL.Bool,
  'imageUrls' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'scope' : IDL.Text,
  'outcomes' : IDL.Text,
  'materials' : IDL.Vec(IDL.Text),
  'category' : ProjectCategory,
});
export const InquiryId = IDL.Nat;
export const ServiceType = IDL.Variant({
  'Interior' : IDL.Null,
  'Architectural' : IDL.Null,
  'SpacePlanning' : IDL.Null,
  'Consultation' : IDL.Null,
  'Renovation' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const Inquiry = IDL.Record({
  'id' : InquiryId,
  'serviceType' : ServiceType,
  'projectDescription' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'timestamp' : Timestamp,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'addHeroImage' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'changeAdminCredentials' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'createProject' : IDL.Func([ProjectInput], [ProjectId], []),
  'deleteProject' : IDL.Func(
      [ProjectId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'getFeaturedProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getHeroImages' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getInquiry' : IDL.Func([InquiryId], [IDL.Opt(Inquiry)], ['query']),
  'getProject' : IDL.Func([ProjectId], [IDL.Opt(Project)], ['query']),
  'listInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'listProjects' : IDL.Func(
      [IDL.Opt(ProjectCategory)],
      [IDL.Vec(Project)],
      ['query'],
    ),
  'removeHeroImage' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'reorderHeroImages' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'setProjectFeatured' : IDL.Func(
      [ProjectId, IDL.Bool],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'submitInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, ServiceType],
      [Inquiry],
      [],
    ),
  'updateProject' : IDL.Func(
      [ProjectId, ProjectInput],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'validateAdminCredentials' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProjectCategory = IDL.Variant({
    'Interior' : IDL.Null,
    'Architectural' : IDL.Null,
    'SpacePlanning' : IDL.Null,
    'Renovation' : IDL.Null,
  });
  const ProjectInput = IDL.Record({
    'title' : IDL.Text,
    'featured' : IDL.Bool,
    'imageUrls' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'scope' : IDL.Text,
    'outcomes' : IDL.Text,
    'materials' : IDL.Vec(IDL.Text),
    'category' : ProjectCategory,
  });
  const ProjectId = IDL.Nat;
  const Project = IDL.Record({
    'id' : ProjectId,
    'title' : IDL.Text,
    'featured' : IDL.Bool,
    'imageUrls' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'scope' : IDL.Text,
    'outcomes' : IDL.Text,
    'materials' : IDL.Vec(IDL.Text),
    'category' : ProjectCategory,
  });
  const InquiryId = IDL.Nat;
  const ServiceType = IDL.Variant({
    'Interior' : IDL.Null,
    'Architectural' : IDL.Null,
    'SpacePlanning' : IDL.Null,
    'Consultation' : IDL.Null,
    'Renovation' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const Inquiry = IDL.Record({
    'id' : InquiryId,
    'serviceType' : ServiceType,
    'projectDescription' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'timestamp' : Timestamp,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'addHeroImage' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'changeAdminCredentials' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'createProject' : IDL.Func([ProjectInput], [ProjectId], []),
    'deleteProject' : IDL.Func(
        [ProjectId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'getFeaturedProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getHeroImages' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getInquiry' : IDL.Func([InquiryId], [IDL.Opt(Inquiry)], ['query']),
    'getProject' : IDL.Func([ProjectId], [IDL.Opt(Project)], ['query']),
    'listInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'listProjects' : IDL.Func(
        [IDL.Opt(ProjectCategory)],
        [IDL.Vec(Project)],
        ['query'],
      ),
    'removeHeroImage' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'reorderHeroImages' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'setProjectFeatured' : IDL.Func(
        [ProjectId, IDL.Bool],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'submitInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, ServiceType],
        [Inquiry],
        [],
      ),
    'updateProject' : IDL.Func(
        [ProjectId, ProjectInput],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'validateAdminCredentials' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };