/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Inquiry {
  'id' : InquiryId,
  'serviceType' : ServiceType,
  'projectDescription' : string,
  'name' : string,
  'email' : string,
  'timestamp' : Timestamp,
  'phone' : string,
}
export type InquiryId = bigint;
export interface Project {
  'id' : ProjectId,
  'title' : string,
  'featured' : boolean,
  'imageUrls' : Array<string>,
  'description' : string,
  'scope' : string,
  'outcomes' : string,
  'materials' : Array<string>,
  'category' : ProjectCategory,
}
export type ProjectCategory = { 'Interior' : null } |
  { 'Architectural' : null } |
  { 'SpacePlanning' : null } |
  { 'Renovation' : null };
export type ProjectId = bigint;
export interface ProjectInput {
  'title' : string,
  'featured' : boolean,
  'imageUrls' : Array<string>,
  'description' : string,
  'scope' : string,
  'outcomes' : string,
  'materials' : Array<string>,
  'category' : ProjectCategory,
}
export type ServiceType = { 'Interior' : null } |
  { 'Architectural' : null } |
  { 'SpacePlanning' : null } |
  { 'Consultation' : null } |
  { 'Renovation' : null };
export interface Stat { 'title' : string, 'value' : string }
export type Timestamp = bigint;
export interface _SERVICE {
  'addHeroImage' : ActorMethod<[string], bigint>,
  'changeAdminCredentials' : ActorMethod<
    [string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'createProject' : ActorMethod<[ProjectInput], ProjectId>,
  'deleteProject' : ActorMethod<
    [ProjectId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'getFeaturedProjects' : ActorMethod<[], Array<Project>>,
  'getHeroImages' : ActorMethod<[], Array<string>>,
  'getInquiry' : ActorMethod<[InquiryId], [] | [Inquiry]>,
  'getProject' : ActorMethod<[ProjectId], [] | [Project]>,
  'getStats' : ActorMethod<[], Array<Stat>>,
  'listInquiries' : ActorMethod<[], Array<Inquiry>>,
  'listProjects' : ActorMethod<[[] | [ProjectCategory]], Array<Project>>,
  'removeHeroImage' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'reorderHeroImages' : ActorMethod<[Array<string>], undefined>,
  'setProjectFeatured' : ActorMethod<
    [ProjectId, boolean],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'submitInquiry' : ActorMethod<
    [string, string, string, string, ServiceType],
    Inquiry
  >,
  'updateProject' : ActorMethod<
    [ProjectId, ProjectInput],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateStats' : ActorMethod<[Array<Stat>], undefined>,
  'validateAdminCredentials' : ActorMethod<[string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];