/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface ProjectInput {
    title: string;
    featured: boolean;
    imageUrls: Array<string>;
    description: string;
    scope: string;
    outcomes: string;
    materials: Array<string>;
    category: ProjectCategory;
}
export type InquiryId = bigint;
export type ProjectId = bigint;
export interface Project {
    id: ProjectId;
    title: string;
    featured: boolean;
    imageUrls: Array<string>;
    description: string;
    scope: string;
    outcomes: string;
    materials: Array<string>;
    category: ProjectCategory;
}
export interface Inquiry {
    id: InquiryId;
    serviceType: ServiceType;
    projectDescription: string;
    name: string;
    email: string;
    timestamp: Timestamp;
    phone: string;
}
export enum ProjectCategory {
    Interior = "Interior",
    Architectural = "Architectural",
    SpacePlanning = "SpacePlanning",
    Renovation = "Renovation"
}
export enum ServiceType {
    Interior = "Interior",
    Architectural = "Architectural",
    SpacePlanning = "SpacePlanning",
    Consultation = "Consultation",
    Renovation = "Renovation"
}
export interface backendInterface {
    addHeroImage(url: string): Promise<bigint>;
    changeAdminCredentials(currentPassword: string, newUsername: string, newPassword: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    createProject(data: ProjectInput): Promise<ProjectId>;
    deleteProject(id: ProjectId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getFeaturedProjects(): Promise<Array<Project>>;
    getHeroImages(): Promise<Array<string>>;
    getInquiry(id: InquiryId): Promise<Inquiry | null>;
    getProject(id: ProjectId): Promise<Project | null>;
    listInquiries(): Promise<Array<Inquiry>>;
    listProjects(category: ProjectCategory | null): Promise<Array<Project>>;
    removeHeroImage(index: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    reorderHeroImages(newOrder: Array<string>): Promise<void>;
    setProjectFeatured(id: ProjectId, featured: boolean): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    submitInquiry(name: string, email: string, phone: string, projectDescription: string, serviceType: ServiceType): Promise<Inquiry>;
    updateProject(id: ProjectId, data: ProjectInput): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    validateAdminCredentials(username: string, password: string): Promise<boolean>;
}
import type { Inquiry as _Inquiry, InquiryId as _InquiryId, Project as _Project, ProjectCategory as _ProjectCategory, ProjectId as _ProjectId, ProjectInput as _ProjectInput, ServiceType as _ServiceType, Timestamp as _Timestamp } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addHeroImage(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addHeroImage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addHeroImage(arg0);
            return result;
        }
    }
    async changeAdminCredentials(arg0: string, arg1: string, arg2: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.changeAdminCredentials(arg0, arg1, arg2);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.changeAdminCredentials(arg0, arg1, arg2);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async createProject(arg0: ProjectInput): Promise<ProjectId> {
        if (this.processError) {
            try {
                const result = await this.actor.createProject(to_candid_ProjectInput_n2(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProject(to_candid_ProjectInput_n2(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteProject(arg0: ProjectId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProject(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProject(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeaturedProjects(): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeaturedProjects();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeaturedProjects();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHeroImages(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHeroImages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHeroImages();
            return result;
        }
    }
    async getInquiry(arg0: InquiryId): Promise<Inquiry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInquiry(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInquiry(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProject(arg0: ProjectId): Promise<Project | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProject(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProject(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async listInquiries(): Promise<Array<Inquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.listInquiries();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listInquiries();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async listProjects(arg0: ProjectCategory | null): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProjects(to_candid_opt_n18(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProjects(to_candid_opt_n18(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeHeroImage(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.removeHeroImage(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeHeroImage(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async reorderHeroImages(arg0: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reorderHeroImages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reorderHeroImages(arg0);
            return result;
        }
    }
    async setProjectFeatured(arg0: ProjectId, arg1: boolean): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.setProjectFeatured(arg0, arg1);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setProjectFeatured(arg0, arg1);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitInquiry(arg0: string, arg1: string, arg2: string, arg3: string, arg4: ServiceType): Promise<Inquiry> {
        if (this.processError) {
            try {
                const result = await this.actor.submitInquiry(arg0, arg1, arg2, arg3, to_candid_ServiceType_n19(this._uploadFile, this._downloadFile, arg4));
                return from_candid_Inquiry_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitInquiry(arg0, arg1, arg2, arg3, to_candid_ServiceType_n19(this._uploadFile, this._downloadFile, arg4));
            return from_candid_Inquiry_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProject(arg0: ProjectId, arg1: ProjectInput): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProject(arg0, to_candid_ProjectInput_n2(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProject(arg0, to_candid_ProjectInput_n2(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async validateAdminCredentials(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.validateAdminCredentials(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateAdminCredentials(arg0, arg1);
            return result;
        }
    }
}
function from_candid_Inquiry_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Inquiry): Inquiry {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_ProjectCategory_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProjectCategory): ProjectCategory {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Project_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Project): Project {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceType_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceType): ServiceType {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Inquiry]): Inquiry | null {
    return value.length === 0 ? null : from_candid_Inquiry_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Project]): Project | null {
    return value.length === 0 ? null : from_candid_Project_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _InquiryId;
    serviceType: _ServiceType;
    projectDescription: string;
    name: string;
    email: string;
    timestamp: _Timestamp;
    phone: string;
}): {
    id: InquiryId;
    serviceType: ServiceType;
    projectDescription: string;
    name: string;
    email: string;
    timestamp: Timestamp;
    phone: string;
} {
    return {
        id: value.id,
        serviceType: from_candid_ServiceType_n14(_uploadFile, _downloadFile, value.serviceType),
        projectDescription: value.projectDescription,
        name: value.name,
        email: value.email,
        timestamp: value.timestamp,
        phone: value.phone
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ProjectId;
    title: string;
    featured: boolean;
    imageUrls: Array<string>;
    description: string;
    scope: string;
    outcomes: string;
    materials: Array<string>;
    category: _ProjectCategory;
}): {
    id: ProjectId;
    title: string;
    featured: boolean;
    imageUrls: Array<string>;
    description: string;
    scope: string;
    outcomes: string;
    materials: Array<string>;
    category: ProjectCategory;
} {
    return {
        id: value.id,
        title: value.title,
        featured: value.featured,
        imageUrls: value.imageUrls,
        description: value.description,
        scope: value.scope,
        outcomes: value.outcomes,
        materials: value.materials,
        category: from_candid_ProjectCategory_n9(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_variant_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Interior: null;
} | {
    Architectural: null;
} | {
    SpacePlanning: null;
} | {
    Renovation: null;
}): ProjectCategory {
    return "Interior" in value ? ProjectCategory.Interior : "Architectural" in value ? ProjectCategory.Architectural : "SpacePlanning" in value ? ProjectCategory.SpacePlanning : "Renovation" in value ? ProjectCategory.Renovation : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Interior: null;
} | {
    Architectural: null;
} | {
    SpacePlanning: null;
} | {
    Consultation: null;
} | {
    Renovation: null;
}): ServiceType {
    return "Interior" in value ? ServiceType.Interior : "Architectural" in value ? ServiceType.Architectural : "SpacePlanning" in value ? ServiceType.SpacePlanning : "Consultation" in value ? ServiceType.Consultation : "Renovation" in value ? ServiceType.Renovation : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Inquiry>): Array<Inquiry> {
    return value.map((x)=>from_candid_Inquiry_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Project>): Array<Project> {
    return value.map((x)=>from_candid_Project_n7(_uploadFile, _downloadFile, x));
}
function to_candid_ProjectCategory_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectCategory): _ProjectCategory {
    return to_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function to_candid_ProjectInput_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectInput): _ProjectInput {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_ServiceType_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceType): _ServiceType {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectCategory | null): [] | [_ProjectCategory] {
    return value === null ? candid_none() : candid_some(to_candid_ProjectCategory_n4(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    featured: boolean;
    imageUrls: Array<string>;
    description: string;
    scope: string;
    outcomes: string;
    materials: Array<string>;
    category: ProjectCategory;
}): {
    title: string;
    featured: boolean;
    imageUrls: Array<string>;
    description: string;
    scope: string;
    outcomes: string;
    materials: Array<string>;
    category: _ProjectCategory;
} {
    return {
        title: value.title,
        featured: value.featured,
        imageUrls: value.imageUrls,
        description: value.description,
        scope: value.scope,
        outcomes: value.outcomes,
        materials: value.materials,
        category: to_candid_ProjectCategory_n4(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceType): {
    Interior: null;
} | {
    Architectural: null;
} | {
    SpacePlanning: null;
} | {
    Consultation: null;
} | {
    Renovation: null;
} {
    return value == ServiceType.Interior ? {
        Interior: null
    } : value == ServiceType.Architectural ? {
        Architectural: null
    } : value == ServiceType.SpacePlanning ? {
        SpacePlanning: null
    } : value == ServiceType.Consultation ? {
        Consultation: null
    } : value == ServiceType.Renovation ? {
        Renovation: null
    } : value;
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectCategory): {
    Interior: null;
} | {
    Architectural: null;
} | {
    SpacePlanning: null;
} | {
    Renovation: null;
} {
    return value == ProjectCategory.Interior ? {
        Interior: null
    } : value == ProjectCategory.Architectural ? {
        Architectural: null
    } : value == ProjectCategory.SpacePlanning ? {
        SpacePlanning: null
    } : value == ProjectCategory.Renovation ? {
        Renovation: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
